source
| extend
    TimeGenerated = todatetime(TimeGenerated),
    AzLocation    = tostring(AzLocation),
    AzZone        = tostring(AzZone),
    VmInstance    = tostring(VmInstance),
    TestType      = tostring(TestType),
    Target        = tostring(Target),
    Protocol      = tostring(Protocol),
    LatencyMs     = toint(LatencyMs),
    Success       = tobool(Success),
    StatusCode    = tostring(StatusCode),
    Error         = tostring(Error),
    CorrelationId = tostring(CorrelationId)
