# This is a workflow to Login in Azure with Federated Credentials

name: Run Azure CLI Login with OpenID Connect
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  contents: read
      
jobs:
  login:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
