name: Environment secrets check

on:
  workflow_dispatch:
  
jobs:
  noenv:
    runs-on: ubuntu-latest
    #environment: production  # Specify the environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Environment Secret
        run: echo "The secret is ${{ secrets.AZURE_CLIENT_ID }}"

  withenv:
    runs-on: ubuntu-latest
    environment: DEV  # Specify the environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Environment Secret
        run: echo "The secret is ${{ secrets.AZURE_CLIENT_ID }}"
